HR_RULE_INPUT = [
    ('HS100', 'Heure Supplémentaire 100% (Heures)', 'HS100'), 
    ('HS75', 'Heure Supplémentaire 75% (Heures)', 'HS75'),
    ('HS50', 'Heure Supplémentaire 50% (Heures)', 'HS50'),
    ('INDC', 'Indemnité de congé (DA)', 'INDC'),
    ('ACMP', 'Acompte (DA)', 'ACOMP'), ('R_ACMP', 'Régularisation Acompte (DA)', 'R_ACOMP'),
    ('R_P8M', 'Régularisation de prime 8 Mars (DA)', 'R_P8M'),
    ('R_PSCL', 'Régularisation de prime de scolarité (DA)', 'R_PSCL'),
    ('R_EXEP', 'Régularisation de prime Exceptionnelle (DA)', 'R_EXEP'),
    ('R_PRC', 'Régularisation de prime de rendement collectif (DA)', 'R_PRC'),
    ('R_IFRI', "Régularisation d'indemnité de frais de résidence et d'isolement (DA)", 'R_IFRI'), 
    ('R_IZCV', "Régularisation d'indemnité de zone et de conditions de vie (DA)", 'R_IZCV'),
    ('R_REMP', 'Régularisation de remboursement de prêt (DA)', 'R_REMP'),
    ('R_RESTO', 'Régulatrisation de frais de restauration (DA)', 'R_RESTO'),
    ('R_FDEP', 'Régularisation de frais de déplacement (DA)', 'R_FRMS'),
    ('R_IVP', "Régularisation d'indemnité de véhicule particulier (DA)", 'R_IVP'),
    ('R_ETRG', "Régularisation d'allocation salarié de nationalité étrangère (DA)", 'R_ETRG'),
    ('R_FRMS', 'Régularisation de frais de mission (DA)', 'R_FDEP'),
    ('R_IK', "Régularisation d'indemnité kilométrique (DA)", 'R_IK'),
    ('R_HEBR', "Régularisation de frais d'hébergement (DA)", 'R_HEBR'),
    ('R_ALOMAT', "Régularisation d'llocation maternité (DA)", 'R_ALOMAT'),
    ('R_PRET', 'Régularisation de prêt (DA)', 'R_PRET'),
    ('R_CHOM', "Réguarisation d'allocation chômage (DA)", 'R_CHOM'),
    ('R_ALOF1', "Régularisation d'allocation familliale (enfant à 300da) (DA)", 'R_ALOF1'),
    ('R_ALOF2', "Régularisation d'allocation familliale (enfant à 600da) (DA)", 'R_ALOF2'),
    ('R_ISUQ', "Régularisation d'indemnité pour salaire unique (IPSU) (DA)", 'R_ISUQ'),
    ('R_BASE', 'Régularisation de salaire de base (DA)', 'R_BASE'),
    ('R_ABS', "Régularisation d'absence jours (DA)", 'R_ABS'),
    ('R_ABSH', "Régularisation d'absence heures (DA)", 'R_ABSH'),
    ('R_IM', 'Régularisation de congé impayé (DA)', 'R_IM'),
    ('R_CM', 'Régularisation de congé maladie (DA)', 'R_CM'),
    ('R_CMM', 'Régularisation de congé maternité (DA)', 'R_CMM'),
    ('R_IRG', "Régularisation d'impot sur le revenus global (IRG) (DA)", 'R_IRG'),
    ('R_IRGC', "Régularisation d'IRG consultant (DA)", 'R_IRGC'),
    ('R_RTMU', 'Régularisation de retenue mutuelle (DA)', 'R_RTMU'),
    ('R_IRG10', "Régularisation d'IRG 10% (DA)", 'R_IRG10'),
    ('R_IRG15', "Régularisation d'IRG 15% (DA)", 'R_IRG15'),
    ('R_IEP', "Régularisation de l'IEP (DA)", 'R_IEP'),
    ('R_TEL', 'Régularisation de prime de téléphone (DA)', 'R_TEL'),
    ('R_IPAN', "Régularisation d'indemnité de panier (DA)", 'R_IPAN'),
    ('R_ITRS', "Régularisation d'indemnité de transport (DA)", 'R_ITRS'),
    ('R_PR', 'Régularisation de prime de responsabilité (DA)', 'R_PR'),
    ('R_NUIS', 'Régularisation de prime de nuisance (DA)', 'R_NUIS'),
    ('R_DANG', 'Régularisation de prime de danger (DA)', 'R_DANG'),
    ('R_PRI', 'Régularisation de prime de rendement individuel (DA)', 'R_PRI'),
    ('R_ICR', "Régularisation d'indemnité de changement de résidence (DA)", 'R_ICR'),
    ('R_CP', 'Régularisation de congé payé (DA)', 'R_CP'),
    ('R_HS50', 'Régularisation des HEURES SUP 50% (DA)', 'R_HS50'),
    ('R_HS75', 'Régularisation des HEURES SUP 75% (DA)', 'R_HS75'),
    ('R_HS100', 'Régularisation des HEURES SUP 100% (DA)', 'R_HS100'),
    ('R_INDC', "Régularisation d'indemnité de congé (DA)", 'R_INDC'),
    ('R_IFSP', "Régularisation de l'IFSP (DA)", 'R_IFSP'),
    ('R_IFS', "Régularisation de l'IFS (DA)", 'R_IFS'),
    ('R_SS', 'Régularisation de sécurité social (DA)', 'R_SS'),
    ('R_BATH', 'Régularisation de cacobath (DA)', 'R_BATH'),
    ('R_TRPST10', "Régularisation d'indemnité travail posté a 10% (05h à 21h) (DA)", 'R_TRPST10'),
    ('R_TRPST15', "Régularisation d'indemnité travail posté a 10% + 5% (21h à 00h) (DA)", 'R_TRPST15'),
    ('R_TRPST25', "Régularisation d'indemnité travail posté a 10% + 15% (00h à 15h) (DA)", 'R_TRPST25'),
    ('R_ASTR', "Régularisation d'astreinte et de disponibilité permenenant (DA)", 'R_ASTR'),
    ('R_ENSG', "Régularisation d'indemnité des activités d'enseignement (DA)", 'R_ENSG'),
    ('R_GESRES', "Régularisation d'indemnité de gestion et de responsabilité (DA)", 'R_GESRES'),
    ('R_ACTR', "Régularisation d'indemnité des activités de contrôle (DA)", 'R_ACTR'),
    ('R_DOCU', "Régularisation d'indemnité de documentation (DA)", 'R_DOCU'),
    ('R_INSPC', "Régularisation d'indemnité de suivi et d'inspection (DA)", 'R_INSPC'),
    ('R_ZONE1', "Régularisation d'indemnité de zone géographique 1 (hauts plateaux) (DA)", 'R_ZONE1'),
    ('R_ZONE2', "Régularisation d'indemnité de zone géographique 2 (sud) (DA)", 'R_ZONE2'),
    ('R_CAIS', 'Régularisation de prime de caisse (DA)', 'R_CAIS'),
    ('R_APRN', "Régularisation de prime de maître d'apprentissage (DA)", 'R_APRN')
]