from . import finn_declaration_cotisation
from . import finn_cotisation_line
from . import finn_abatement_base
from . import finn_movement_employees
from . import finn_declaration_das
from . import finn_lot_declaration_cotisation
from . import res_company
from . import hr_employee
from . import res_partner
from . import finn_activity_code