from . import finn_hr_salary_rule
from . import finn_hr_payslip
from . import finn_hr_payslip_run
from . import finn_hr_payslip_input
from . import hr_contract
from . import hr_employee
from . import res_config_settings
from . import hr_leave
from . import finn_hr_annual_leave
from . import hr_leave_allocation
